-- ============================================================
-- Controle Financeiro Familiar - Supabase/PostgreSQL
-- Execute no SQL Editor do Supabase.
-- A chave de serviço deve ser usada somente no backend.
-- ============================================================

CREATE TABLE IF NOT EXISTS usuarios (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" VARCHAR(50)  NOT NULL UNIQUE,
  email VARCHAR(254)  NOT NULL UNIQUE,
  senha VARCHAR(255)  NOT NULL,
  nome  VARCHAR(100)  NOT NULL
);

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email VARCHAR(254);
CREATE UNIQUE INDEX IF NOT EXISTS usuarios_email_key ON usuarios (email);

CREATE TABLE IF NOT EXISTS movimentacoes (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id  INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  tipo        VARCHAR(20) NOT NULL CHECK (tipo IN ('gasto', 'receita')),
  descricao   VARCHAR(255) NOT NULL,
  categoria   VARCHAR(100),
  pessoa      VARCHAR(100),
  valor       NUMERIC(10, 2) NOT NULL CHECK (valor > 0),
  data        DATE NOT NULL,
  criado_em   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_movimentacoes_usuario_data
  ON movimentacoes (usuario_id, data DESC);

ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimentacoes ENABLE ROW LEVEL SECURITY;
